import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from '../store/ReduxProvider';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-gray-900"
      ><ReduxProvider>
        {children}</ReduxProvider>
      </body>
    </html>
  );
}
